# Project 3 - Reddit Classification: Powerlifting vs. Bodybuilding

# Data Cleaning

In [1]:
import pandas as pd

In [2]:
powerlifting = pd.read_csv('data/powerlifting.csv')
bodybuilding = pd.read_csv('data/bodybuilding.csv')

In [3]:
powerlifting.head()

,id,created_utc,title,self_text,subreddit,all_text
0,844947,1.520949e+09,My 64 yr old mom breaking RPS 60-64 age/198 lb...,NaN,powerlifting,My 64 yr old mom breaking RPS 60-64 age/198 lb...
1,9s6nh4,1.540760e+09,Lifter with Cerebral Palsy. This is what power...,NaN,powerlifting,Lifter with Cerebral Palsy. This is what power...
2,gc9nq6,1.588438e+09,Hafthor Bjornsson deadlifts 501kg,NaN,powerlifting,Hafthor Bjornsson deadlifts 501kg
3,12fz87c,1.680990e+09,"Finally hit 400 lbs in a meet!! 402.3 lbs, 48 ...",NaN,powerlifting,"Finally hit 400 lbs in a meet!! 402.3 lbs, 48 ..."
4,aoauyd,1.549587e+09,A true power lifter,NaN,powerlifting,A true power lifter

In [4]:
powerlifting.shape

(998, 6)

In [5]:
bodybuilding.head()

,id,created_utc,title,self_text,subreddit,all_text
0,cxjwqb,1.567185e+09,"To my best friend, Franco",NaN,bodybuilding,"To my best friend, Franco"
1,93fatt,1.533050e+09,Thank you all for pumping me up on my birthday,NaN,bodybuilding,Thank you all for pumping me up on my birthday
2,ik6fqj,1.598907e+09,It is back day,NaN,bodybuilding,It is back day
3,97umxn,1.534443e+09,I got my 1969 Mr. Universe class trophy back!,NaN,bodybuilding,I got my 1969 Mr. Universe class trophy back!
4,968445,1.533916e+09,One of my rules is... break the rules,NaN,bodybuilding,One of my rules is... break the rules

In [6]:
bodybuilding.shape

(992, 6)

In [7]:
# combine data into one dataframe
powerlifting_bodybuilding = pd.concat([powerlifting, bodybuilding], ignore_index=True)
powerlifting_bodybuilding

,id,created_utc,title,self_text,subreddit,all_text
0,844947,1.520949e+09,My 64 yr old mom breaking RPS 60-64 age/198 lb...,NaN,powerlifting,My 64 yr old mom breaking RPS 60-64 age/198 lb...
1,9s6nh4,1.540760e+09,Lifter with Cerebral Palsy. This is what power...,NaN,powerlifting,Lifter with Cerebral Palsy. This is what power...
2,gc9nq6,1.588438e+09,Hafthor Bjornsson deadlifts 501kg,NaN,powerlifting,Hafthor Bjornsson deadlifts 501kg
3,12fz87c,1.680990e+09,"Finally hit 400 lbs in a meet!! 402.3 lbs, 48 ...",NaN,powerlifting,"Finally hit 400 lbs in a meet!! 402.3 lbs, 48 ..."
4,aoauyd,1.549587e+09,A true power lifter,NaN,powerlifting,A true power lifter
...,...,...,...,...,...,...
1985,j8x9lb,1.602383e+09,Super happy with a gold and silver at my first...,NaN,bodybuilding,Super happy with a gold and silver at my first...
1986,ccpjdj,1.563026e+09,Light weight!,NaN,bodybuilding,Light weight!
1987,73p5f2,1.506901e+09,"Seen a lot of freaks on the sub latley, so her...",NaN,bodybuilding,"Seen a lot of freaks on the sub latley, so her..."
1988,ii0p1b,1.598590e+09,"Classic Physique Athlete Corey Becker, beginni...",NaN,bodybuilding,"Classic Physique Athlete Corey Becker, beginni..."
1989,jwjz09,1.605720e+09,"Ahhhh Shit. Mustache back, Courtney back. CBum...",NaN,bodybuilding,"Ahhhh Shit. Mustache back, Courtney back. CBum..."

In [8]:
powerlifting_bodybuilding.shape

(1990, 6)

In [9]:
powerlifting_bodybuilding.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1990 entries, 0 to 1989
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           1990 non-null   object
 1   created_utc  1990 non-null   float64
 2   title        1990 non-null   object
 3   self_text    177 non-null    object
 4   subreddit    1990 non-null   object
 5   all_text     1990 non-null   object
dtypes: float64(1), object(5)
memory usage: 93.4+ KB

In [10]:
powerlifting_bodybuilding.isna().sum()

id                0
created_utc       0
title             0
self_text      1813
subreddit         0
all_text          0
dtype: int64

In [11]:
powerlifting_bodybuilding['self_text'].fillna('None', inplace=True)

In [12]:
powerlifting_bodybuilding.isna().sum()

id             0
created_utc    0
title          0
self_text      0
subreddit      0
all_text       0
dtype: int64

In [13]:
powerlifting_bodybuilding.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1990 entries, 0 to 1989
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           1990 non-null   object
 1   created_utc  1990 non-null   float64
 2   title        1990 non-null   object
 3   self_text    1990 non-null   object
 4   subreddit    1990 non-null   object
 5   all_text     1990 non-null   object
dtypes: float64(1), object(5)
memory usage: 93.4+ KB

In [14]:
powerlifting_bodybuilding.head()

,id,created_utc,title,self_text,subreddit,all_text
0,844947,1.520949e+09,My 64 yr old mom breaking RPS 60-64 age/198 lb...,None,powerlifting,My 64 yr old mom breaking RPS 60-64 age/198 lb...
1,9s6nh4,1.540760e+09,Lifter with Cerebral Palsy. This is what power...,None,powerlifting,Lifter with Cerebral Palsy. This is what power...
2,gc9nq6,1.588438e+09,Hafthor Bjornsson deadlifts 501kg,None,powerlifting,Hafthor Bjornsson deadlifts 501kg
3,12fz87c,1.680990e+09,"Finally hit 400 lbs in a meet!! 402.3 lbs, 48 ...",None,powerlifting,"Finally hit 400 lbs in a meet!! 402.3 lbs, 48 ..."
4,aoauyd,1.549587e+09,A true power lifter,None,powerlifting,A true power lifter

In [15]:
powerlifting_bodybuilding.tail()

,id,created_utc,title,self_text,subreddit,all_text
1985,j8x9lb,1.602383e+09,Super happy with a gold and silver at my first...,None,bodybuilding,Super happy with a gold and silver at my first...
1986,ccpjdj,1.563026e+09,Light weight!,None,bodybuilding,Light weight!
1987,73p5f2,1.506901e+09,"Seen a lot of freaks on the sub latley, so her...",None,bodybuilding,"Seen a lot of freaks on the sub latley, so her..."
1988,ii0p1b,1.598590e+09,"Classic Physique Athlete Corey Becker, beginni...",None,bodybuilding,"Classic Physique Athlete Corey Becker, beginni..."
1989,jwjz09,1.605720e+09,"Ahhhh Shit. Mustache back, Courtney back. CBum...",None,bodybuilding,"Ahhhh Shit. Mustache back, Courtney back. CBum..."

In [16]:
# replace 'powerlifting' with 1 and 'bodybuilding' with 2
powerlifting_bodybuilding['subreddit'] = powerlifting_bodybuilding['subreddit'].replace({'powerlifting': 1, 'bodybuilding': 2})

In [17]:
powerlifting_bodybuilding.head()

,id,created_utc,title,self_text,subreddit,all_text
0,844947,1.520949e+09,My 64 yr old mom breaking RPS 60-64 age/198 lb...,None,1,My 64 yr old mom breaking RPS 60-64 age/198 lb...
1,9s6nh4,1.540760e+09,Lifter with Cerebral Palsy. This is what power...,None,1,Lifter with Cerebral Palsy. This is what power...
2,gc9nq6,1.588438e+09,Hafthor Bjornsson deadlifts 501kg,None,1,Hafthor Bjornsson deadlifts 501kg
3,12fz87c,1.680990e+09,"Finally hit 400 lbs in a meet!! 402.3 lbs, 48 ...",None,1,"Finally hit 400 lbs in a meet!! 402.3 lbs, 48 ..."
4,aoauyd,1.549587e+09,A true power lifter,None,1,A true power lifter

In [18]:
powerlifting_bodybuilding.tail()

,id,created_utc,title,self_text,subreddit,all_text
1985,j8x9lb,1.602383e+09,Super happy with a gold and silver at my first...,None,2,Super happy with a gold and silver at my first...
1986,ccpjdj,1.563026e+09,Light weight!,None,2,Light weight!
1987,73p5f2,1.506901e+09,"Seen a lot of freaks on the sub latley, so her...",None,2,"Seen a lot of freaks on the sub latley, so her..."
1988,ii0p1b,1.598590e+09,"Classic Physique Athlete Corey Becker, beginni...",None,2,"Classic Physique Athlete Corey Becker, beginni..."
1989,jwjz09,1.605720e+09,"Ahhhh Shit. Mustache back, Courtney back. CBum...",None,2,"Ahhhh Shit. Mustache back, Courtney back. CBum..."

In [19]:
# save combined data to csv file
powerlifting_bodybuilding.to_csv('data/powerlifting_bodybuilding.csv', index=False)